2017-02-20 14:05:52,795-ERROR-_calcImg:..\..\..\src\opencv\modules\imgproc\src\shapedescr.cpp:799: error: (-201) Number of points should be >= 5
Traceback (most recent call last):
  File "D:\MyProjects\WorkProject\opencv4fiber\geomety\GUI\model\modecv.py", line 95, in _calcImg
    self.eresults = self.classify.find(img)
  File "D:\MyProjects\WorkProject\opencv4fiber\geomety\pattern\classify.py", line 201, in find
    coreResult = PickCircle().run(coreimg)
  File "D:\MyProjects\WorkProject\opencv4fiber\geomety\pattern\pickmethod.py", line 34, in run
    ellipse = cv2.fitEllipse(mergedpoints)
error: ..\..\..\src\opencv\modules\imgproc\src\shapedescr.cpp:799: error: (-201) Number of points should be >= 5

2017-02-20 15:24:45,413-ERROR-_calcImg:
Traceback (most recent call last):
  File "D:\MyProjects\WorkProject\opencv4fiber\geomety\GUI\model\modecv.py", line 95, in _calcImg
    self.eresults = self.classify.find(img)
  File "D:\MyProjects\WorkProject\opencv4fiber\geomety\pattern\classify.py", line 201, in find
    coreResult = PickCircle().run(coreimg)
  File "D:\MyProjects\WorkProject\opencv4fiber\geomety\pattern\pickmethod.py", line 29, in run
    raise ClassCoreError
ClassCoreError
2017-02-23 10:22:44,072-ERROR-_calcImg:
Traceback (most recent call last):
  File "D:\MyProjects\WorkProject\opencv4fiber\geomety\GUI\model\modecv.py", line 95, in _calcImg
    self.eresults = self.classify.find(img)
  File "D:\MyProjects\WorkProject\opencv4fiber\geomety\pattern\classify.py", line 201, in find
    coreResult = PickCircle().run(coreimg)
  File "D:\MyProjects\WorkProject\opencv4fiber\geomety\pattern\pickmethod.py", line 29, in run
    raise ClassCoreError
ClassCoreError
2017-02-23 14:11:10,888-ERROR-_calcImg:
Traceback (most recent call last):
  File "D:\MyProjects\WorkProject\opencv4fiber\geomety\GUI\model\modecv.py", line 95, in _calcImg
    self.eresults = self.classify.find(img)
  File "D:\MyProjects\WorkProject\opencv4fiber\geomety\pattern\classify.py", line 231, in find
    coreResult = PickCircle().run(coreimg)
  File "D:\MyProjects\WorkProject\opencv4fiber\geomety\pattern\pickmethod.py", line 29, in run
    raise ClassCoreError
ClassCoreError
2017-03-06 12:21:14,798-ERROR-_calcImg:
Traceback (most recent call last):
  File "D:\MyProjects\WorkProject\opencv4fiber\geomety\GUI\model\modecv.py", line 93, in _calcImg
    self.eresults = self.classify.find(img)
  File "D:\MyProjects\WorkProject\opencv4fiber\geomety\pattern\classify.py", line 231, in find
    coreResult = PickCircle().run(coreimg)
  File "D:\MyProjects\WorkProject\opencv4fiber\geomety\pattern\pickmethod.py", line 29, in run
    raise ClassCoreError
ClassCoreError
2017-03-06 12:52:16,595-ERROR-_calcImg:
Traceback (most recent call last):
  File "D:\MyProjects\WorkProject\opencv4fiber\geomety\GUI\model\modecv.py", line 93, in _calcImg
    self.eresults = self.classify.find(img)
  File "D:\MyProjects\WorkProject\opencv4fiber\geomety\pattern\classify.py", line 231, in find
    coreResult = PickCircle().run(coreimg)
  File "D:\MyProjects\WorkProject\opencv4fiber\geomety\pattern\pickmethod.py", line 29, in run
    raise ClassCoreError
ClassCoreError
2017-03-06 12:52:47,000-ERROR-_calcImg:
Traceback (most recent call last):
  File "D:\MyProjects\WorkProject\opencv4fiber\geomety\GUI\model\modecv.py", line 93, in _calcImg
    self.eresults = self.classify.find(img)
  File "D:\MyProjects\WorkProject\opencv4fiber\geomety\pattern\classify.py", line 231, in find
    coreResult = PickCircle().run(coreimg)
  File "D:\MyProjects\WorkProject\opencv4fiber\geomety\pattern\pickmethod.py", line 29, in run
    raise ClassCoreError
ClassCoreError
2017-03-06 12:55:43,158-ERROR-_calcImg:
Traceback (most recent call last):
  File "D:\MyProjects\WorkProject\opencv4fiber\geomety\GUI\model\modecv.py", line 93, in _calcImg
    self.eresults = self.classify.find(img)
  File "D:\MyProjects\WorkProject\opencv4fiber\geomety\pattern\classify.py", line 231, in find
    coreResult = PickCircle().run(coreimg)
  File "D:\MyProjects\WorkProject\opencv4fiber\geomety\pattern\pickmethod.py", line 29, in run
    raise ClassCoreError
ClassCoreError
2017-03-06 12:58:14,289-ERROR-_calcImg:
Traceback (most recent call last):
  File "D:\MyProjects\WorkProject\opencv4fiber\geomety\GUI\model\modecv.py", line 93, in _calcImg
    self.eresults = self.classify.find(img)
  File "D:\MyProjects\WorkProject\opencv4fiber\geomety\pattern\classify.py", line 231, in find
    coreResult = PickCircle().run(coreimg)
  File "D:\MyProjects\WorkProject\opencv4fiber\geomety\pattern\pickmethod.py", line 29, in run
    raise ClassCoreError
ClassCoreError
2017-03-06 13:22:50,108-ERROR-_calcImg:
Traceback (most recent call last):
  File "D:\MyProjects\WorkProject\opencv4fiber\geomety\GUI\model\modecv.py", line 93, in _calcImg
    self.eresults = self.classify.find(img)
  File "D:\MyProjects\WorkProject\opencv4fiber\geomety\pattern\classify.py", line 236, in find
    coreResult = PickCircle().run(coreimg)
  File "D:\MyProjects\WorkProject\opencv4fiber\geomety\pattern\pickmethod.py", line 29, in run
    raise ClassCoreError
ClassCoreError
2017-03-06 13:25:38,819-ERROR-_calcImg:
Traceback (most recent call last):
  File "D:\MyProjects\WorkProject\opencv4fiber\geomety\GUI\model\modecv.py", line 93, in _calcImg
    self.eresults = self.classify.find(img)
  File "D:\MyProjects\WorkProject\opencv4fiber\geomety\pattern\classify.py", line 236, in find
    coreResult = PickCircle().run(coreimg)
  File "D:\MyProjects\WorkProject\opencv4fiber\geomety\pattern\pickmethod.py", line 29, in run
    raise ClassCoreError
ClassCoreError
2017-03-06 13:27:51,786-ERROR-_calcImg:unbound method run() must be called with ExtractEdge instance as first argument (got ndarray instance instead)
Traceback (most recent call last):
  File "D:\MyProjects\WorkProject\opencv4fiber\geomety\GUI\model\modecv.py", line 93, in _calcImg
    self.eresults = self.classify.find(img)
  File "D:\MyProjects\WorkProject\opencv4fiber\geomety\pattern\classify.py", line 232, in find
    cladimg = ExtractEdge.run(cladimg)
TypeError: unbound method run() must be called with ExtractEdge instance as first argument (got ndarray instance instead)
2017-03-06 13:28:19,321-ERROR-_calcImg:unbound method run() must be called with ExtractEdge instance as first argument (got ndarray instance instead)
Traceback (most recent call last):
  File "D:\MyProjects\WorkProject\opencv4fiber\geomety\GUI\model\modecv.py", line 93, in _calcImg
    self.eresults = self.classify.find(img)
  File "D:\MyProjects\WorkProject\opencv4fiber\geomety\pattern\classify.py", line 232, in find
    cladimg = ExtractEdge.run(cladimg)
TypeError: unbound method run() must be called with ExtractEdge instance as first argument (got ndarray instance instead)
2017-03-06 13:52:37,111-ERROR-_calcImg:
Traceback (most recent call last):
  File "D:\MyProjects\WorkProject\opencv4fiber\geomety\GUI\model\modecv.py", line 93, in _calcImg
    self.eresults = self.classify.find(img)
  File "D:\MyProjects\WorkProject\opencv4fiber\geomety\pattern\classify.py", line 237, in find
    coreResult = PickCircle().run(coreimg)
  File "D:\MyProjects\WorkProject\opencv4fiber\geomety\pattern\pickmethod.py", line 29, in run
    raise ClassCoreError
ClassCoreError
